"""JARVIS Built-in Native Capability Manifests.

Provides declarative manifests for standard core capabilities:
- File System Read/Write
- Shell Command Execution
- Web Fetch
- System Clock
"""

from jarvis.core.capabilities.manifest import (
    CapabilityManifest,
    RiskClass,
    SideEffectClass,
    ToolType,
)
from jarvis.core.capabilities.registry import CapabilityRegistry
from jarvis.core.ifc.sinks import SinkType
from jarvis.core.trust.taxonomy import TrustLevel

BUILTIN_CAPABILITIES: list[CapabilityManifest] = [
    CapabilityManifest(
        capability_id="native:fs:read_file",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Reads the complete text content of a specified file within the allowed workspace.",
        required_scopes=["filesystem:read"],
        input_schema={
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Absolute or relative file path"}
            },
            "required": ["file_path"],
        },
        output_schema={"type": "object", "properties": {"content": {"type": "string"}}},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:fs:write_file",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Writes or overwrites text content to a specified file within the allowed workspace.",
        required_scopes=["filesystem:write"],
        input_schema={
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Path of the file to write"},
                "content": {"type": "string", "description": "Text content to write"},
            },
            "required": ["file_path", "content"],
        },
        output_schema={"type": "object", "properties": {"bytes_written": {"type": "integer"}}},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.FILE_SYSTEM_WRITE],
        sandbox_requirement=False,
        approval_requirement=True,
    ),
    CapabilityManifest(
        capability_id="native:fs:delete_file",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Deletes a specified file within the allowed workspace boundary.",
        required_scopes=["filesystem:delete"],
        input_schema={
            "type": "object",
            "properties": {
                "file_path": {"type": "string", "description": "Path of the file to delete"}
            },
            "required": ["file_path"],
        },
        output_schema={"type": "object", "properties": {"status": {"type": "string"}}},
        risk_class=RiskClass.DANGEROUS,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.FILE_SYSTEM_WRITE],
        sandbox_requirement=False,
        approval_requirement=True,
        verification_requirement=True,
    ),
    CapabilityManifest(
        capability_id="native:shell:execute",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.SANDBOX,
        description="Executes a command within an isolated execution sandbox runner.",
        required_scopes=["shell:execute"],
        input_schema={
            "type": "object",
            "properties": {
                "command": {"type": "string", "description": "Command line string to execute"},
                "timeout_seconds": {"type": "integer", "default": 30},
            },
            "required": ["command"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "stdout": {"type": "string"},
                "stderr": {"type": "string"},
                "exit_code": {"type": "integer"},
            },
        },
        risk_class=RiskClass.DANGEROUS,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.SHELL_EXECUTION],
        sandbox_requirement=True,
        approval_requirement=True,
        verification_requirement=True,
    ),
    CapabilityManifest(
        capability_id="native:code:run_test",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description=(
            "HOST PROCESS EXECUTION: Executes a workspace-local Python test or script via direct host subprocess "
            "execution (shell=False). CAUTION: Does not provide OS-level container isolation "
            "(sandbox_status=NOT_ISOLATED); process retains host user permissions and network access. "
            "Requires explicit human authorization."
        ),
        required_scopes=["code:execute"],
        input_schema={
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "description": "Workspace-relative path to Python file (.py)",
                },
                "mode": {
                    "type": "string",
                    "enum": ["script", "pytest"],
                    "default": "script",
                },
                "test_args": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional safe argument flags",
                },
                "timeout_seconds": {"type": "number", "default": 30.0},
            },
            "required": ["file_path"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "file_path": {"type": "string"},
                "exit_code": {"type": "integer"},
                "stdout": {"type": "string"},
                "stderr": {"type": "string"},
                "duration_seconds": {"type": "number"},
                "timed_out": {"type": "boolean"},
                "truncated": {"type": "boolean"},
            },
        },
        risk_class=RiskClass.UNBOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.SHELL_EXECUTION],
        sandbox_requirement=True,
        approval_requirement=True,
        verification_requirement=True,
    ),
    CapabilityManifest(
        capability_id="sandbox:code:execute",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.SANDBOX,
        description=(
            "CONTAINER SANDBOX EXECUTION: Executes a script, test suite, or command inside an isolated "
            "container sandbox (TIER_1_CONTAINER) with Linux kernel namespaces, dropped capabilities, "
            "no-new-privileges, cgroup resource limits, and read-only rootfs. Fails closed if host lacks "
            "an operational container backend. Never falls back to host execution."
        ),
        required_scopes=["code:execute", "sandbox:execute"],
        input_schema={
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Command list to execute within the isolated container",
                },
                "files": {
                    "type": "object",
                    "description": "Optional mapping of relative workspace paths to text content to write",
                },
                "timeout_seconds": {"type": "number", "default": 30.0},
            },
            "required": ["command"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "exit_code": {"type": "integer"},
                "stdout": {"type": "string"},
                "stderr": {"type": "string"},
                "duration_seconds": {"type": "number"},
                "timed_out": {"type": "boolean"},
                "sandbox_id": {"type": "string"},
                "isolation_tier": {"type": "string"},
                "provider_category": {"type": "string"},
                "sandbox_status": {"type": "string"},
            },
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.SHELL_EXECUTION],
        sandbox_requirement=True,
        approval_requirement=False,
        verification_requirement=True,
    ),
    CapabilityManifest(
        capability_id="native:web:fetch",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Fetches raw content from a permitted remote HTTP/HTTPS URL.",
        required_scopes=["network:fetch"],
        input_schema={
            "type": "object",
            "properties": {"url": {"type": "string", "description": "HTTP or HTTPS URL to fetch"}},
            "required": ["url"],
        },
        output_schema={
            "type": "object",
            "properties": {"status_code": {"type": "integer"}, "body": {"type": "string"}},
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.EXTERNAL_NETWORK, SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:web:search",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Searches the live web and returns matching titles, URLs, and snippets.",
        required_scopes=["network:fetch"],
        input_schema={
            "type": "object",
            "properties": {"query": {"type": "string", "description": "Search query keywords"}},
            "required": ["query"],
        },
        output_schema={
            "type": "object",
            "properties": {"results": {"type": "array"}, "count": {"type": "integer"}},
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.EXTERNAL_NETWORK, SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:clock:get_time",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Returns the current UTC ISO-8601 system timestamp.",
        required_scopes=["system:clock"],
        input_schema={"type": "object", "properties": {}},
        output_schema={"type": "object", "properties": {"utc_iso": {"type": "string"}}},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:calc:evaluate",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Safely evaluates mathematical and arithmetic expressions using an AST evaluator.",
        required_scopes=["math:evaluate"],
        input_schema={
            "type": "object",
            "properties": {
                "expression": {"type": "string", "description": "Mathematical expression string"}
            },
            "required": ["expression"],
        },
        output_schema={"type": "object", "properties": {"result": {"type": "number"}}},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:fs:list_dir",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Lists files and subdirectories within a permitted directory.",
        required_scopes=["filesystem:read"],
        input_schema={
            "type": "object",
            "properties": {"dir_path": {"type": "string", "description": "Directory path to list"}},
        },
        output_schema={"type": "object", "properties": {"entries": {"type": "array"}}},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:system:get_stats",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Retrieves host operating system, CPU, memory, and disk health metrics.",
        required_scopes=["system:status"],
        input_schema={"type": "object", "properties": {}},
        output_schema={
            "type": "object",
            "properties": {
                "platform": {"type": "string"},
                "cpu_percent": {"type": "number"},
                "memory_percent": {"type": "number"},
                "disk_percent": {"type": "number"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:artifact:read_slice",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Reads a deterministic window of lines from an offloaded Data-Plane artifact.",
        required_scopes=["artifact:read"],
        input_schema={
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string",
                    "description": "Task ID associated with the artifact",
                },
                "artifact_id": {
                    "type": "string",
                    "description": "Unique identifier of the artifact",
                },
                "offset": {
                    "type": "integer",
                    "description": "Starting line offset (0-indexed)",
                    "default": 0,
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of lines to return",
                    "default": 100,
                },
            },
            "required": ["task_id", "artifact_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "artifact_id": {"type": "string"},
                "task_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "total_lines": {"type": "integer"},
                "has_more": {"type": "boolean"},
                "next_page_token": {"type": ["string", "null"]},
                "content": {"type": "string"},
                "lines_returned": {"type": "integer"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:artifact:get_metadata",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Retrieves metadata and physical storage characteristics for an offloaded Data-Plane artifact.",
        required_scopes=["artifact:read"],
        input_schema={
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string",
                    "description": "Task ID associated with the artifact",
                },
                "artifact_id": {
                    "type": "string",
                    "description": "Unique identifier of the artifact",
                },
            },
            "required": ["task_id", "artifact_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "artifact_id": {"type": "string"},
                "task_id": {"type": "string"},
                "file_name": {"type": "string"},
                "file_path": {"type": "string"},
                "size_bytes": {"type": "integer"},
                "suffix": {"type": "string"},
                "created_timestamp": {"type": "number"},
                "modified_timestamp": {"type": "number"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:memory:write",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description=(
            "Writes or updates a record in the Governed Memory Plane with optimistic concurrency "
            "control, supersession tracking, and epistemic status calibration."
        ),
        required_scopes=["memory:write"],
        input_schema={
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "USER_PREFERENCE",
                        "PROJECT_FACT",
                        "SYSTEM_PROCEDURE",
                        "EPISODIC_NOTE",
                        "SESSION_SUMMARY",
                    ],
                    "description": "Category of the memory record",
                },
                "key": {
                    "type": "string",
                    "description": "Key or topic under which memory is filed",
                },
                "content": {
                    "type": "string",
                    "description": "Textual information or knowledge to retain",
                },
                "expected_version": {
                    "type": "integer",
                    "description": "Optional OCC expected version for atomic revision",
                },
                "tenant_id": {"type": "string", "default": "default"},
                "user_id": {"type": "string", "default": "default_user"},
                "epistemic_status": {
                    "type": "string",
                    "enum": [
                        "PROPOSED",
                        "OBSERVED",
                        "VERIFIED_INTERNAL",
                        "VERIFIED_EXTERNAL",
                    ],
                    "default": "PROPOSED",
                },
                "source_trust_level": {
                    "type": "string",
                    "default": "EXTERNAL_UNTRUSTED",
                },
            },
            "required": ["category", "key", "content"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "memory_id": {"type": "string"},
                "key": {"type": "string"},
                "version": {"type": "integer"},
                "epistemic_status": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.FILE_SYSTEM_WRITE, SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:memory:query",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description=(
            "Queries the Governed Memory Plane with categorical, key, and point-in-time (as_of) filtering."
        ),
        required_scopes=["memory:read"],
        input_schema={
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "USER_PREFERENCE",
                        "PROJECT_FACT",
                        "SYSTEM_PROCEDURE",
                        "EPISODIC_NOTE",
                        "SESSION_SUMMARY",
                    ],
                    "description": "Optional category filter",
                },
                "key": {"type": "string", "description": "Optional key or topic prefix to look up"},
                "as_of": {
                    "type": "string",
                    "description": "Optional ISO timestamp for point-in-time query",
                },
                "tenant_id": {"type": "string", "default": "default"},
                "user_id": {"type": "string", "default": "default_user"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "count": {"type": "integer"},
                "records": {"type": "array"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:app:launch",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Launches an operating system desktop application asynchronously.",
        required_scopes=["os:app:launch"],
        input_schema={
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string",
                    "description": "Name or executable of the application (e.g. 'notepad', 'calc', 'chrome')",
                },
                "args": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional command-line arguments to pass to the application",
                },
            },
            "required": ["app_name"],
        },
        output_schema={
            "type": "object",
            "properties": {"pid": {"type": "integer"}, "status": {"type": "string"}},
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.PROCESS_SPAWN],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:app:close",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Gracefully closes or terminates running applications by process name or PID.",
        required_scopes=["os:app:close"],
        input_schema={
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string",
                    "description": "Name or PID of the application to close (e.g. 'notepad', 'chrome')",
                },
                "force": {
                    "type": "boolean",
                    "default": False,
                    "description": "Whether to forcefully kill the process",
                },
            },
            "required": ["app_name"],
        },
        output_schema={
            "type": "object",
            "properties": {"terminated_pids": {"type": "array"}, "count": {"type": "integer"}},
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.PROCESS_SPAWN],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:app:list",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Lists active user-space running applications and background tasks.",
        required_scopes=["os:app:list"],
        input_schema={
            "type": "object",
            "properties": {
                "filter_name": {
                    "type": "string",
                    "description": "Optional substring to filter application names",
                },
                "limit": {
                    "type": "integer",
                    "default": 50,
                    "description": "Maximum number of processes to return",
                },
            },
        },
        output_schema={
            "type": "object",
            "properties": {"count": {"type": "integer"}, "processes": {"type": "array"}},
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:screen:capture",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Captures active desktop display frame for visual grounding and multi-modal perception.",
        required_scopes=["screen:capture", "os:vision"],
        input_schema={
            "type": "object",
            "properties": {
                "output_format": {
                    "type": "string",
                    "default": "base64",
                    "enum": ["base64", "bytes"],
                },
                "max_dimension": {"type": "integer", "default": 1280},
                "quality": {"type": "integer", "default": 80},
                "monitor_index": {"type": "integer", "default": 1},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "base64_data": {"type": "string"},
                "mime_type": {"type": "string"},
                "byte_size": {"type": "integer"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:screen:click",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects a synthetic mouse click at specific absolute or normalized screen coordinates.",
        required_scopes=["screen:click", "os:input"],
        input_schema={
            "type": "object",
            "properties": {
                "x": {
                    "type": "number",
                    "description": "X coordinate in pixels or 0.0-1.0 normalized",
                },
                "y": {
                    "type": "number",
                    "description": "Y coordinate in pixels or 0.0-1.0 normalized",
                },
                "button": {
                    "type": "string",
                    "default": "left",
                    "enum": ["left", "right", "middle"],
                },
                "clicks": {"type": "integer", "default": 1},
                "normalized": {"type": "boolean", "default": False},
            },
            "required": ["x", "y"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "status": {"type": "string"},
                "message": {"type": "string"},
            },
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:screen:type",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects synthetic keyboard keystrokes or text into the currently active foreground window.",
        required_scopes=["screen:type", "os:input"],
        input_schema={
            "type": "object",
            "properties": {
                "text": {"type": "string", "description": "Text content to type"},
                "press_enter": {"type": "boolean", "default": False},
                "interval": {"type": "number", "default": 0.01},
            },
            "required": ["text"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "characters_typed": {"type": "integer"},
                "status": {"type": "string"},
            },
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:screen:hotkey",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Triggers a system keyboard shortcut or hotkey combination (e.g. ['ctrl', 's']).",
        required_scopes=["screen:hotkey", "os:input"],
        input_schema={
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of key names to press simultaneously",
                },
            },
            "required": ["keys"],
        },
        output_schema={
            "type": "object",
            "properties": {"keys": {"type": "array"}, "status": {"type": "string"}},
        },
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="native:screen:get_window",
        owner="core",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Inspects the title, geometry, and coordinates of the active foreground desktop window.",
        required_scopes=["screen:window", "os:window"],
        input_schema={"type": "object", "properties": {}},
        output_schema={
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "left": {"type": "integer"},
                "top": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
            },
        },
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[
            TrustLevel.USER_INPUT,
            TrustLevel.SYSTEM_POLICY,
            TrustLevel.EXTERNAL_UNTRUSTED,
        ],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    # ---------------------------------------------------------
    # Governed Computer Control Subsystem Capabilities (22 capabilities)
    # ---------------------------------------------------------
    CapabilityManifest(
        capability_id="computer:screenshot",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Captures the live desktop screen frame with dimension metadata and DPI awareness.",
        required_scopes=["screen:capture"],
        input_schema={
            "type": "object",
            "properties": {
                "max_dimension": {
                    "type": "integer",
                    "description": "Maximum width/height dimension for downscaling",
                },
                "quality": {"type": "integer", "description": "JPEG compression quality 1-100"},
                "monitor_index": {"type": "integer", "description": "1-indexed target monitor"},
                "output_format": {"type": "string", "enum": ["bytes", "base64", "both"]},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:inspect_ui",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Inspects Windows UI Automation accessibility element hierarchy of target or foreground window.",
        required_scopes=["os:window", "screen:window"],
        input_schema={
            "type": "object",
            "properties": {
                "window_title": {"type": "string", "description": "Target window title substring"},
                "hwnd": {"type": "integer", "description": "Target window handle"},
                "max_elements": {"type": "integer", "description": "Max elements to discover"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:ui:inspect",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Alias for computer:inspect_ui for accessibility hierarchy inspection.",
        required_scopes=["os:window", "screen:window"],
        input_schema={
            "type": "object",
            "properties": {
                "window_title": {"type": "string", "description": "Target window title substring"},
                "hwnd": {"type": "integer", "description": "Target window handle"},
                "max_elements": {"type": "integer", "description": "Max elements to discover"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:resolve_target",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Dynamically discovers real UI Automation control, acquires exact physical coordinates, and validates observation state.",
        required_scopes=["os:window", "screen:window", "screen:ui"],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Accessible name or semantic query"},
                "element_query": {"type": "string", "description": "Accessible name query"},
                "semantic_role": {"type": "string", "description": "Optional UIA control type"},
                "window_title": {"type": "string", "description": "Target window title substring"},
                "hwnd": {"type": "integer", "description": "Target window handle"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:click_element",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Dynamically locates and clicks a real UI Automation control without guessing coordinates.",
        required_scopes=["screen:click", "screen:ui"],
        input_schema={
            "type": "object",
            "properties": {
                "element_query": {"type": "string", "description": "Accessible name query"},
                "query": {"type": "string", "description": "Accessible name or semantic query"},
                "semantic_role": {"type": "string", "description": "Optional UIA control type"},
                "window_title": {"type": "string", "description": "Target window title substring"},
                "button": {"type": "string", "enum": ["left", "right", "middle"]},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:click",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects mouse click at coordinates or semantic UI element with visual state verification.",
        required_scopes=["screen:click"],
        input_schema={
            "type": "object",
            "properties": {
                "x": {"type": "number", "description": "Horizontal coordinate"},
                "y": {"type": "number", "description": "Vertical coordinate"},
                "button": {"type": "string", "enum": ["left", "right", "middle"]},
                "clicks": {"type": "integer", "description": "Number of clicks"},
                "normalized": {
                    "type": "boolean",
                    "description": "True if coordinates are normalized [0, 999]",
                },
                "element_query": {
                    "type": "string",
                    "description": "Accessible name query for semantic click",
                },
                "window_title": {
                    "type": "string",
                    "description": "Optional window title confinement",
                },
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:double_click",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects double mouse click at coordinates or semantic UI element.",
        required_scopes=["screen:click"],
        input_schema={
            "type": "object",
            "properties": {
                "x": {"type": "number"},
                "y": {"type": "number"},
                "normalized": {"type": "boolean"},
                "element_query": {"type": "string"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:right_click",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects right mouse click (context menu) at coordinates or semantic UI element.",
        required_scopes=["screen:click"],
        input_schema={
            "type": "object",
            "properties": {
                "x": {"type": "number"},
                "y": {"type": "number"},
                "normalized": {"type": "boolean"},
                "element_query": {"type": "string"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:move_mouse",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Moves mouse cursor to target coordinates.",
        required_scopes=["screen:cursor"],
        input_schema={
            "type": "object",
            "properties": {
                "x": {"type": "number"},
                "y": {"type": "number"},
                "normalized": {"type": "boolean"},
            },
            "required": ["x", "y"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:drag",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Drags mouse cursor from starting coordinates to ending coordinates.",
        required_scopes=["screen:click"],
        input_schema={
            "type": "object",
            "properties": {
                "from_x": {"type": "number"},
                "from_y": {"type": "number"},
                "to_x": {"type": "number"},
                "to_y": {"type": "number"},
                "normalized": {"type": "boolean"},
            },
            "required": ["from_x", "from_y", "to_x", "to_y"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:type",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects keyboard text into currently focused control with visual verification.",
        required_scopes=["screen:type"],
        input_schema={
            "type": "object",
            "properties": {
                "text": {"type": "string", "description": "Text to type"},
                "press_enter": {"type": "boolean", "description": "Press enter after typing"},
                "element_query": {
                    "type": "string",
                    "description": "Optional UI element query to focus before typing",
                },
                "window_title": {
                    "type": "string",
                    "description": "Optional target window title substring",
                },
                "recipient": {
                    "type": "string",
                    "description": "Optional intended recipient validation for messaging",
                },
            },
            "required": ["text"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:press_key",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Presses a single keyboard key (e.g. enter, tab, escape, backspace).",
        required_scopes=["screen:hotkey"],
        input_schema={
            "type": "object",
            "properties": {"key": {"type": "string"}},
            "required": ["key"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:hotkey",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Triggers a system keyboard shortcut combination.",
        required_scopes=["screen:hotkey"],
        input_schema={
            "type": "object",
            "properties": {
                "keys": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["keys"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:scroll",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Injects vertical mouse wheel scroll deltas with visual change verification.",
        required_scopes=["screen:scroll"],
        input_schema={
            "type": "object",
            "properties": {
                "clicks": {"type": "integer", "description": "Positive for up, negative for down"}
            },
            "required": ["clicks"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:focus_window",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Brings a window matching query or HWND to foreground.",
        required_scopes=["os:window"],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "hwnd": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:minimize_window",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Minimizes a window matching query or HWND.",
        required_scopes=["os:window"],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "hwnd": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:maximize_window",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Maximizes a window matching query or HWND.",
        required_scopes=["os:window"],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "hwnd": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:close_window",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Gracefully closes a window matching query or HWND via WM_CLOSE with state verification.",
        required_scopes=["os:window", "os:app:manage"],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "hwnd": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.INPUT_INJECTION],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:launch_app",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Launches desktop application via 7-source resolution pipeline with physical window verification.",
        required_scopes=["os:app:manage"],
        input_schema={
            "type": "object",
            "properties": {
                "app_name": {"type": "string", "description": "Application name or alias"},
                "args": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional CLI arguments",
                },
            },
            "required": ["app_name"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.BOUNDED_MUTATION,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.PROCESS_SPAWN],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:list_windows",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Lists all visible top-level desktop windows with titles and geometries on the interactive desktop.",
        required_scopes=["os:window", "screen:window"],
        input_schema={
            "type": "object",
            "properties": {
                "include_invisible": {"type": "boolean"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:list_apps",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Lists discoverable installed applications from Start Menu and registry App Paths.",
        required_scopes=["os:app:manage"],
        input_schema={
            "type": "object",
            "properties": {
                "limit": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:list_processes",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Lists active host processes correlated with visible top-level windows.",
        required_scopes=["os:app:manage"],
        input_schema={
            "type": "object",
            "properties": {
                "filter_name": {"type": "string"},
                "limit": {"type": "integer"},
            },
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:terminate_process",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Terminates a process by PID with protected system process blacklist enforcement (requires HITL).",
        required_scopes=["os:app:manage"],
        input_schema={
            "type": "object",
            "properties": {
                "pid": {"type": "integer"},
                "force": {"type": "boolean"},
            },
            "required": ["pid"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.DANGEROUS,
        side_effect_class=SideEffectClass.NON_IDEMPOTENT,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.PROCESS_SPAWN],
        sandbox_requirement=False,
        approval_requirement=True,
    ),
    CapabilityManifest(
        capability_id="computer:wait",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Pauses execution for bounded seconds to allow UI animations or transitions to complete.",
        required_scopes=["system:clock"],
        input_schema={
            "type": "object",
            "properties": {
                "seconds": {"type": "number"},
            },
            "required": ["seconds"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
    CapabilityManifest(
        capability_id="computer:verify_visual_state",
        owner="computer",
        version="1.0.0",
        provider="builtin",
        tool_type=ToolType.NATIVE,
        description="Verifies that desktop visual display state changed by comparing pre- and post-action digests.",
        required_scopes=["screen:capture"],
        input_schema={
            "type": "object",
            "properties": {
                "pre_screenshot_digest": {"type": "string"},
            },
            "required": ["pre_screenshot_digest"],
        },
        output_schema={"type": "object"},
        risk_class=RiskClass.READ_ONLY,
        side_effect_class=SideEffectClass.NONE,
        allowed_trust_sources=[TrustLevel.USER_INPUT, TrustLevel.SYSTEM_POLICY],
        allowed_sinks=[SinkType.LLM_PROMPT],
        sandbox_requirement=False,
        approval_requirement=False,
    ),
]


def register_builtin_capabilities(registry: CapabilityRegistry) -> None:
    """Register all standard built-in capabilities into the registry."""
    for manifest in BUILTIN_CAPABILITIES:
        manifest.seal()
        registry.register(manifest, verify_digest=True)
