"""JARVIS Capability Specialist Base Interface.

Defines the foundation for domain capability specialists (ARCHITECTURE.md Layer 8 & 10).
Specialists produce PROPOSALS; the shared platform enforces security and policy.
"""

from abc import ABC, abstractmethod
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class SpecialistRole(StrEnum):
    """The five canonical capability specialist roles (ARCHITECTURE.md Layer 8)."""

    RESEARCH = "research"
    """Deep search, retrieval, citation, and evidence extraction."""

    CODING = "coding"
    """Filesystem, code analysis, refactoring, and test execution."""

    COMPUTER = "computer"
    """OS automation, process/filesystem observation, and system commands."""

    PERSONAL = "personal"
    """Calendar, preferences, personal memory, and messaging with strict privacy."""

    ANALYSIS = "analysis"
    """Deterministic math, structured transforms, data analytics, and evaluation."""


class SpecialistProposal(BaseModel):
    """A proposed action or response generated by a specialist."""

    proposal_id: UUID = Field(default_factory=uuid4)
    specialist_role: SpecialistRole
    intent: str
    tool_id: str | None = None
    arguments: dict[str, Any] = Field(default_factory=dict)
    direct_response: str | None = None
    needs_clarification: bool = False
    clarification_question: str | None = None
    target_resource: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class SpecialistManifest(BaseModel):
    """Declarative capability specialist manifest."""

    name: str
    role: SpecialistRole
    role_description: str
    allowed_tool_scopes: list[str] = Field(default_factory=list)
    memory_mode: str = "PER_SPECIALIST"


class BaseSpecialist(ABC):
    """Abstract interface for all JARVIS capability specialists."""

    def __init__(self, manifest: SpecialistManifest) -> None:
        self.manifest = manifest

    @property
    def role(self) -> SpecialistRole:
        return self.manifest.role

    @abstractmethod
    async def propose(
        self,
        user_message: str,
        context: dict[str, Any] | None = None,
    ) -> SpecialistProposal:
        """Analyze user input and produce a tool proposal, direct answer, or clarifying question."""
        pass

    async def process_task(self, task_payload: dict[str, Any]) -> dict[str, Any]:
        """Process an assigned task and return structured output."""
        msg = task_payload.get("message") or task_payload.get("prompt") or str(task_payload)
        proposal = await self.propose(msg)
        return proposal.model_dump(mode="json")

    @abstractmethod
    async def synthesize(
        self,
        proposal: SpecialistProposal,
        tool_result: Any,
        user_message: str,
    ) -> str:
        """Synthesize tool observation results into a user-facing response."""
        pass
