"""Capability Firewall and Canonical Action Rules for JARVIS.

Core Invariant: Every executable capability has a canonical identifier.
The model receives only permitted capabilities and cannot execute arbitrary
unrestricted host primitives.
"""

from typing import Dict, Set

from jarvis.contracts.action import RiskTier

# Canonical capability identifiers
CAPABILITY_FILESYSTEM_READ = "filesystem.read"
CAPABILITY_FILESYSTEM_WRITE = "filesystem.write"
CAPABILITY_FILESYSTEM_DELETE = "filesystem.delete"
CAPABILITY_FILESYSTEM_LIST = "filesystem.list"
CAPABILITY_FILESYSTEM_SEARCH = "filesystem.search"
CAPABILITY_ARTIFACT_DELIVER = "artifact.deliver"

CAPABILITY_PROCESS_ENUMERATE = "process.enumerate"
CAPABILITY_PROCESS_LAUNCH = "process.launch"
CAPABILITY_PROCESS_TERMINATE = "process.terminate"
CAPABILITY_PROCESS_INSPECT = "process.inspect"

CAPABILITY_SHELL_EXECUTE = "shell.execute"

CAPABILITY_COMPUTER_SCREENSHOT = "computer.screenshot"
CAPABILITY_COMPUTER_CLICK = "computer.click"
CAPABILITY_COMPUTER_TYPE = "computer.type"
CAPABILITY_COMPUTER_KEY = "computer.key"
CAPABILITY_COMPUTER_ACT = "computer.act"

CAPABILITY_APP_LAUNCH = "app.launch"
CAPABILITY_WINDOW_FOCUS = "window.focus"
CAPABILITY_WINDOW_CLOSE = "window.close"
CAPABILITY_WINDOW_LIST = "window.list"
CAPABILITY_UI_INSPECT = "ui.inspect"
CAPABILITY_UI_INTERACT = "ui.interact"

CAPABILITY_SYSTEM_VOLUME = "system.volume"
CAPABILITY_SYSTEM_BRIGHTNESS = "system.brightness"
CAPABILITY_SYSTEM_INFO = "system.info"

CAPABILITY_BROWSER_NAVIGATE = "browser.navigate"
CAPABILITY_BROWSER_SNAPSHOT = "browser.snapshot"
CAPABILITY_BROWSER_CLICK = "browser.click"
CAPABILITY_BROWSER_TYPE = "browser.type"
CAPABILITY_BROWSER_SCREENSHOT = "browser.screenshot"

CAPABILITY_WHATSAPP_CALL = "whatsapp.call"
CAPABILITY_WHATSAPP_STATUS = "whatsapp.status"
CAPABILITY_WHATSAPP_HISTORY = "whatsapp.history"
CAPABILITY_WHATSAPP_LOGIN = "whatsapp.login"
CAPABILITY_WHATSAPP_LOGOUT = "whatsapp.logout"
CAPABILITY_WHATSAPP_SYNC = "whatsapp.sync"
CAPABILITY_WHATSAPP_CONTACTS_SEARCH = "whatsapp.contacts.search"
CAPABILITY_WHATSAPP_CONTACTS_GET = "whatsapp.contacts.get"
CAPABILITY_WHATSAPP_CONTACTS_CHECK = "whatsapp.contacts.check"
CAPABILITY_WHATSAPP_CONTACTS_REFRESH = "whatsapp.contacts.refresh"
CAPABILITY_WHATSAPP_CONTACTS_ALIAS = "whatsapp.contacts.alias"
CAPABILITY_WHATSAPP_CONTACTS_TAGS = "whatsapp.contacts.tags"
CAPABILITY_WHATSAPP_CHATS_LIST = "whatsapp.chats.list"
CAPABILITY_WHATSAPP_CHATS_GET = "whatsapp.chats.get"
CAPABILITY_WHATSAPP_CHATS_UNREAD = "whatsapp.chats.unread"
CAPABILITY_WHATSAPP_MESSAGES_LIST = "whatsapp.messages.list"
CAPABILITY_WHATSAPP_MESSAGES_SEARCH = "whatsapp.messages.search"
CAPABILITY_WHATSAPP_MESSAGES_CONTEXT = "whatsapp.messages.context"
CAPABILITY_WHATSAPP_SEND_TEXT = "whatsapp.send.text"
CAPABILITY_WHATSAPP_SEND_FILE = "whatsapp.send.file"
CAPABILITY_WHATSAPP_SEND_VOICE = "whatsapp.send.voice"
CAPABILITY_WHATSAPP_SEND_REACTION = "whatsapp.send.reaction"
CAPABILITY_WHATSAPP_SEND_REPLY = "whatsapp.send.reply"
CAPABILITY_WHATSAPP_REVIEW_UNREAD = "whatsapp.review_unread"
CAPABILITY_WHATSAPP_MEDIA_DOWNLOAD = "whatsapp.media.download"

# Risk tier assignments for each capability
CAPABILITY_RISK_MAP: Dict[str, RiskTier] = {
    CAPABILITY_FILESYSTEM_READ: RiskTier.READ_ONLY,
    CAPABILITY_FILESYSTEM_LIST: RiskTier.READ_ONLY,
    CAPABILITY_FILESYSTEM_SEARCH: RiskTier.READ_ONLY,
    CAPABILITY_ARTIFACT_DELIVER: RiskTier.LOW,
    CAPABILITY_FILESYSTEM_WRITE: RiskTier.MEDIUM,
    CAPABILITY_FILESYSTEM_DELETE: RiskTier.HIGH,
    CAPABILITY_PROCESS_ENUMERATE: RiskTier.READ_ONLY,
    CAPABILITY_PROCESS_INSPECT: RiskTier.READ_ONLY,
    CAPABILITY_PROCESS_LAUNCH: RiskTier.MEDIUM,
    CAPABILITY_PROCESS_TERMINATE: RiskTier.HIGH,
    CAPABILITY_SHELL_EXECUTE: RiskTier.HIGH,
    CAPABILITY_APP_LAUNCH: RiskTier.MEDIUM,
    CAPABILITY_WINDOW_FOCUS: RiskTier.LOW,
    CAPABILITY_WINDOW_CLOSE: RiskTier.MEDIUM,
    CAPABILITY_WINDOW_LIST: RiskTier.READ_ONLY,
    CAPABILITY_UI_INSPECT: RiskTier.READ_ONLY,
    CAPABILITY_UI_INTERACT: RiskTier.MEDIUM,
    CAPABILITY_COMPUTER_SCREENSHOT: RiskTier.READ_ONLY,
    CAPABILITY_COMPUTER_CLICK: RiskTier.MEDIUM,
    CAPABILITY_COMPUTER_TYPE: RiskTier.MEDIUM,
    CAPABILITY_COMPUTER_KEY: RiskTier.MEDIUM,
    CAPABILITY_COMPUTER_ACT: RiskTier.MEDIUM,
    CAPABILITY_SYSTEM_VOLUME: RiskTier.LOW,
    CAPABILITY_SYSTEM_BRIGHTNESS: RiskTier.LOW,
    CAPABILITY_SYSTEM_INFO: RiskTier.READ_ONLY,
    CAPABILITY_BROWSER_NAVIGATE: RiskTier.LOW,
    CAPABILITY_BROWSER_SNAPSHOT: RiskTier.READ_ONLY,
    CAPABILITY_BROWSER_CLICK: RiskTier.MEDIUM,
    CAPABILITY_BROWSER_TYPE: RiskTier.MEDIUM,
    CAPABILITY_BROWSER_SCREENSHOT: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CALL: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_STATUS: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_HISTORY: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_LOGIN: RiskTier.LOW,
    CAPABILITY_WHATSAPP_LOGOUT: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_SYNC: RiskTier.LOW,
    CAPABILITY_WHATSAPP_CONTACTS_SEARCH: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CONTACTS_GET: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CONTACTS_CHECK: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CONTACTS_REFRESH: RiskTier.LOW,
    CAPABILITY_WHATSAPP_CONTACTS_ALIAS: RiskTier.LOW,
    CAPABILITY_WHATSAPP_CONTACTS_TAGS: RiskTier.LOW,
    CAPABILITY_WHATSAPP_CHATS_LIST: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CHATS_GET: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_CHATS_UNREAD: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_MESSAGES_LIST: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_MESSAGES_SEARCH: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_MESSAGES_CONTEXT: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_SEND_TEXT: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_SEND_FILE: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_SEND_VOICE: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_SEND_REACTION: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_SEND_REPLY: RiskTier.MEDIUM,
    CAPABILITY_WHATSAPP_REVIEW_UNREAD: RiskTier.READ_ONLY,
    CAPABILITY_WHATSAPP_MEDIA_DOWNLOAD: RiskTier.READ_ONLY,
}

# Blacklisted dangerous shell substrings that fail-closed immediately
DANGEROUS_SHELL_PATTERNS: Set[str] = {
    "format ",
    "rmdir /s /q c:",
    "del /f /s /q c:",
    ":(){ :|:& };:",
    "drop database",
    "truncate table",
    "diskpart",
    "bcdedit",
    "vssadmin delete shadows",
}


def is_dangerous_command(command: str) -> bool:
    """Check if a shell command matches strictly prohibited destructive patterns."""
    normalized = command.strip().lower()
    for pattern in DANGEROUS_SHELL_PATTERNS:
        if pattern in normalized:
            return True
    return False
