"""JARVIS Realtime Voice Plane Model Adapter Interfaces.

Defines provider-independent contracts for bidirectional realtime streaming audio,
asynchronous function calling, session resumption, context window compression,
GoAway lifecycle signals, and barge-in / interruption semantics.
"""

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class LiveEventType(StrEnum):
    """Categorical classification of incoming realtime events."""

    AUDIO_CHUNK = "AUDIO_CHUNK"
    TEXT_DELTA = "TEXT_DELTA"
    TRANSCRIPTION = "TRANSCRIPTION"
    TOOL_CALL = "TOOL_CALL"
    TOOL_CALL_CANCEL = "TOOL_CALL_CANCEL"
    TURN_COMPLETE = "TURN_COMPLETE"
    GENERATION_COMPLETE = "GENERATION_COMPLETE"
    INTERRUPTED = "INTERRUPTED"
    GO_AWAY = "GO_AWAY"
    RESUMPTION_UPDATE = "RESUMPTION_UPDATE"
    STATUS_CHANGE = "STATUS_CHANGE"
    ERROR = "ERROR"


class LiveAudioChunk(BaseModel):
    """Raw audio bytes emitted from or ingested into the realtime voice plane."""

    data: bytes
    sample_rate: int = 24000
    channels: int = 1
    format: str = "audio/pcm"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveTranscription(BaseModel):
    """Speech-to-text transcription event for user or model audio."""

    text: str
    is_user: bool
    is_final: bool = True
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveToolCall(BaseModel):
    """High-level function invocation proposal generated by the voice model."""

    call_id: str = Field(default_factory=lambda: f"call_{uuid4().hex[:12]}")
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    is_non_blocking: bool = True
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveToolResponse(BaseModel):
    """Authoritative response returned to the voice model following governance verification."""

    call_id: str
    name: str
    response: dict[str, Any]
    scheduling: str = "WHEN_IDLE"  # INTERRUPT, WHEN_IDLE, or SILENT
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveGoAway(BaseModel):
    """Provider-issued connection termination warning requiring transparent session replacement."""

    time_left_seconds: float | None = None
    reason: str = "SCHEDULED_ROTATION"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveResumptionUpdate(BaseModel):
    """Updated session state handle for reconnecting and resuming a conversation."""

    handle: str
    resumable: bool = True
    last_consumed_message_index: int | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveInteractionStatus(StrEnum):
    """Extended thinking and background execution interaction status."""

    IDLE = "IDLE"
    IN_PROGRESS = "IN_PROGRESS"


class LiveEvent(BaseModel):
    """Normalized asynchronous envelope emitted by the realtime model adapter."""

    event_type: LiveEventType
    payload: Any = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LiveSessionConfig(BaseModel):
    """Configuration schema for initiating or resuming a realtime voice session."""

    model_id: str = "gemini-3.8-live"
    system_instruction: str | None = None
    voice_name: str = "Puck"
    tools: list[dict[str, Any]] | None = None
    resumption_handle: str | None = None
    enable_compression: bool = False
    compression_threshold_tokens: int = 80000
    thinking_budget: int | None = None
    thinking_level: str | None = None
    input_transcription: bool = True
    output_transcription: bool = True
    response_modalities: list[str] = Field(default_factory=lambda: ["AUDIO"])


class RealtimeModelAdapter(ABC):
    """Abstract provider interface for bidirectional realtime streaming models."""

    @abstractmethod
    async def connect(self, config: LiveSessionConfig) -> None:
        """Establish bidirectional realtime connection to upstream provider."""
        pass

    @abstractmethod
    async def send_text(self, text: str, end_of_turn: bool = True) -> None:
        """Send conversational text input into active realtime session."""
        pass

    @abstractmethod
    async def send_audio(self, pcm_data: bytes, end_of_turn: bool = False) -> None:
        """Send raw 16kHz 16-bit mono little-endian PCM audio chunk to model."""
        pass

    @abstractmethod
    async def send_tool_response(self, response: LiveToolResponse) -> None:
        """Send verified function response back to the voice model."""
        pass

    @abstractmethod
    def receive_events(self) -> AsyncIterator[LiveEvent]:
        """Asynchronous stream of incoming server events (audio, text, tools, GoAway)."""
        pass

    @abstractmethod
    async def interrupt(self) -> None:
        """Signal client barge-in / interruption to truncate active speech generation."""
        pass

    @abstractmethod
    async def close(self) -> None:
        """Gracefully terminate connection and release local resources."""
        pass

    @abstractmethod
    def get_latest_resumption_handle(self) -> str | None:
        """Retrieve most recent valid session resumption token."""
        pass

    @property
    @abstractmethod
    def connected(self) -> bool:
        """Return True if connection is actively established."""
        pass
