"""FIDES Information-Flow Control (IFC) Dual-Label Model.

Defines orthogonal Integrity and Confidentiality labels, their lattice ranks,
and meet/join mathematical operations governing taint and sensitivity propagation.
"""

from enum import StrEnum


class IntegrityLabel(StrEnum):
    """Integrity dimension of the FIDES labeling architecture.

    Measures the degree to which data is protected against unauthorized tampering
    or originating from untrusted sources.
    Order (lowest to highest): UNTRUSTED < USER_CONTROLLED < SYSTEM_TRUSTED.
    """

    UNTRUSTED = "UNTRUSTED"
    """Data from external or unverifiable sources (web, email, third-party tools)."""

    USER_CONTROLLED = "USER_CONTROLLED"
    """Data directly entered by the authenticated user."""

    SYSTEM_TRUSTED = "SYSTEM_TRUSTED"
    """Data generated by internal invariant components or cryptographically verified."""

    @property
    def rank(self) -> int:
        """Numerical rank of integrity."""
        return _INTEGRITY_RANK[self]

    def is_at_least(self, minimum: "IntegrityLabel") -> bool:
        """Check if self meets or exceeds the required integrity level."""
        return self.rank >= minimum.rank

    def meet(self, other: "IntegrityLabel") -> "IntegrityLabel":
        """Compute the lattice meet (greatest lower bound).

        Taint is contagious: lower integrity dominates.
        """
        return self if self.rank <= other.rank else other


_INTEGRITY_RANK: dict[IntegrityLabel, int] = {
    IntegrityLabel.UNTRUSTED: 0,
    IntegrityLabel.USER_CONTROLLED: 1,
    IntegrityLabel.SYSTEM_TRUSTED: 2,
}


def meet_integrity_labels(*labels: IntegrityLabel) -> IntegrityLabel:
    """Compute the meet (minimum integrity) across multiple labels."""
    if not labels:
        return IntegrityLabel.UNTRUSTED
    return min(labels, key=lambda lbl: lbl.rank)


class ConfidentialityLabel(StrEnum):
    """Confidentiality dimension of the FIDES labeling architecture.

    Measures the sensitivity of the data and constraints on its egress.
    Order (least restrictive to most restrictive):
    PUBLIC < INTERNAL < CONFIDENTIAL < SECRET.
    """

    PUBLIC = "PUBLIC"
    """Non-sensitive data suitable for public dissemination or external network egress."""

    INTERNAL = "INTERNAL"
    """Operational agent data suitable for normal internal orchestration."""

    CONFIDENTIAL = "CONFIDENTIAL"
    """User personal information, sensitive files, private correspondence."""

    SECRET = "SECRET"
    """API keys, passwords, credentials, cryptographic keys. Never flows to external sinks."""

    @property
    def rank(self) -> int:
        """Numerical rank of confidentiality sensitivity."""
        return _CONFIDENTIALITY_RANK[self]

    def is_at_most(self, maximum: "ConfidentialityLabel") -> bool:
        """Check if self is within the allowed confidentiality threshold."""
        return self.rank <= maximum.rank

    def join_label(self, other: "ConfidentialityLabel") -> "ConfidentialityLabel":
        """Compute the lattice join (least upper bound).

        Sensitivity escalates: higher confidentiality dominates.
        """
        return self if self.rank >= other.rank else other

    def escalate(self, other: "ConfidentialityLabel") -> "ConfidentialityLabel":
        """Alias for join_label: higher confidentiality dominates."""
        return self.join_label(other)


_CONFIDENTIALITY_RANK: dict[ConfidentialityLabel, int] = {
    ConfidentialityLabel.PUBLIC: 0,
    ConfidentialityLabel.INTERNAL: 1,
    ConfidentialityLabel.CONFIDENTIAL: 2,
    ConfidentialityLabel.SECRET: 3,
}


def join_confidentiality_labels(*labels: ConfidentialityLabel) -> ConfidentialityLabel:
    """Compute the join (maximum confidentiality) across multiple labels."""
    if not labels:
        return ConfidentialityLabel.PUBLIC
    return max(labels, key=lambda lbl: lbl.rank)
